language: php

php:
- 5.6

addons:
  sauce_connect:
    username:
      secure: "SrwumxTd9BGuU+8GRWPwXHZYpyuojqed1NNhzWbpG0/GiWAH1tDw0WNbDlq5p0wqzhfMOkOBS6V0JLrbUedXlicx824jI2631JDyQ7IJhwlXZtWwGTqrkc0IhdCXrOsHMGQdimq1KVOWdkR+QM8LsqCtATDfCboxH2SLZAjJ7M8="
    access_key:
      secure: "PsZCY8wX7dY9KhFaYgPNCxbr2fSKqA6BWBpbI+xCTbQsxhXyqXMjEERUWvHXge/aUo+tkcc21jFH8qiXYJEdO/iqyeT+58w3fX5GUiwn4W3d+zHAziszy4/PdJ9gEnK5H+fnS0SVLM/No6tETO7mA1ys8o+vFLuWmDkftkRUALI="

services:
  - redis-server
  - elasticsearch
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'create database testdb;'
  - composer self-update
  - composer install --no-interaction
  - npm install -g bower
  - npm install
  - bower install
  - gulp compile
  - php artisan migrate --force
  - php artisan db:seed --class=MetaContextValueSeeder
  - php artisan serve --host=0.0.0.0 > /dev/null 2>&1 &
  - sleep 10

script:
  - vendor/bin/phpunit tests/functional
