js_app:
	@cat boot.js organisations.js locations.js questionnaires.js questionnaire-panel.js questionnaire-saver.js question-creator.js choise-creator.js bootstrap-datepicker.js start.js > ./../master.js
	@echo 'makefile'